### ISSUE TITLE
Cannot install using pip or easy_install

### ISSUE THREAD

**Issue by namchester** [makinacorpus/spynner#75]
error occurs while installing autopy.

src/screen.c:7:23: fatal error: X11/Xlib.h: No such file or directory
  #include <X11/Xlib.h>
                       ^
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by hurzl** [comment]
```# locate X11/Xlib.h
/usr/local/include/X11/Xlib.h
```
It the include path, how do I change it?

**Comment by kiorky** [comment]
installation problem, not a bug.
